# Generated by Django 5.1.4 on 2025-12-11 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_cashier_photo_passenger_photo_trip_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='number',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='train_type',
        ),
        migrations.AlterField(
            model_name='cashier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='people/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='people/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.cashier'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(blank=True, default='Cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='arrival',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='capacity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
