# Generated by Django 5.1.4 on 2025-12-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_ticket_purchase_date_remove_trip_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='number',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
