# Generated by Django 5.1.4 on 2025-12-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_trip_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='train_type',
            field=models.CharField(default='Regular', max_length=100),
        ),
    ]
