# Generated by Django 5.1.4 on 2025-12-11 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_trip_train_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_tickets', to='tickets.cashier'),
        ),
    ]
