# Generated by Django 6.0 on 2025-12-12 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # dependencies = [
    #     ('tickets'),
    # ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.cashier'),
        ),
    ]
